[tools]
node = "latest"
cargo-binstall = "latest"
"cargo:tree-sitter-cli" = "latest"
"go:github.com/jesseduffield/lazygit" = "latest"
"go:github.com/jesseduffield/lazydocker" = "latest"
uv = "latest"
"pipx:trash-cli" = "latest"
"pipx:poetry" = "latest"
"cargo:ast-grep" = "latest"
"ubi:koalaman/shellcheck" = "latest"
"go:mvdan.cc/sh/v3/cmd/shfmt" = "latest"
"pipx:djlint" = "latest"
"pipx:yamllint" = "latest"
"ubi:google/yamlfmt" = "latest"
"npm:@fsouza/prettierd" = "latest"

[settings]
experimental = true
pipx_uvx = true
asdf = true
vfox = true
